title: "奉昌炜 Bruce's Homepage"
page-top-title: 奉昌炜 Bruce
top-section-bg-text: Data Science / Web3
backgrounds:
  - static/assets/background/background_0.jpeg
background-interval-ms: 7000
background-overlay: 0.52
copyright-text: '&copy; 奉昌炜 Bruce 2023-2027. All Rights Reserved.'
github-link:
  text: Github
  href: https://github.com/LBStruggleee
license-link:
  text: License
  href: https://github.com/LBStruggleee/LBStruggleee.github.io/blob/main/LICENSE
sections:
  - id: home
    nav: HOME
    title: 奉昌炜 Bruce
    href: '#page-top'
  - id: projects
    nav: PROJECTS
    title: PROJECTS
    icon: bi-code-slash
